shared:
  is_a_bot: &a4
    - or:
        - author=cloudpossebot
        - author=github-actions[bot]
        - author=dependabot[bot]
        - author=renovate[bot]
        - author=cloudposse-releaser[bot]
  not_a_bot: &a1
    - and:
        - -author=cloudpossebot
        - -author=github-actions[bot]
        - -author=dependabot[bot]
        - -author=renovate[bot]
        - author=cloudposse-releaser[bot]
  is_external_contributor: &a13
    - and:
        - -author=@engineering
        - -author=@contributors
        - -author=@admins
        - -author=@bots
        - -author=@approvers
        - -author=@security
        - and: *a1
  is_default_branch: &a8
    - or:
        - base=main
        - base=master
  is_release_branch:
    - and:
        - base~=^release/v\d{1,2}$
  not_wip: &a11
    - and:
        - -title~=^(wip|WIP)
        - -label~=(WIP|wip|do-not-merge|do not merge|triage|stale|feedback|help
          needed)
        - -draft
  needs_attention: &a3
    - and:
        - label~=(triage|stale|feedback|help needed)
  do_not_merge: &a2
    - or:
        - label~=(do-not-merge|do not merge)
        - title~=(do-not-merge|do not merge)
  is_wip: &a9
    - or:
        - title~=^(wip|WIP)
        - label~=(WIP|wip)
        - and: *a2
        - and: *a3
        - draft
  not_in_conflict: &a12
    - and:
        - -conflict
        - -label~=(conflict)
  pr_has_metadata:
    - and:
        - title~=(^[0-9A-Za-z]+)
        - body~=[0-9A-Za-z]{3,}\\s+[0-9A-Za-z]{3,}\\s+[0-9A-Za-z]{3,}
        - -body~=(Describe high-level what changed)
  is_approved:
    - and:
        - "#approved-reviews-by>=1"
        - "#changes-requested-reviews-by=0"
        - "#review-threads-unresolved=0"
        - "#commented-reviews-by=0"
  checks_are_passing:
    - and:
        - "#check-pending=0"
        - "#status-failure=0"
  require_terraform_checks_are_passing: &a15
    - or:
        - -files~=\.tf$
        - and:
            - check-success=test/bats
            - check-success=test/terratest
            - -status-failure~=^(terratest|terraform)$
  require_codeowners_checks_are_passing:
    - or:
        - -files=CODEOWNERS
        - and:
            - check-success=validate-codeowners
  is_terraform: &a7
    - and:
        - files~=\.tf$
  is_open: &a5
    - and:
        - -merged
        - -closed
  is_recent_commit: &a14
    - and:
        - commits[*].date_committer > 1 minutes ago
  readme_updated:
    - or:
        - and:
            - -files=README.md
            - -files=README.yaml
        - and:
            - files=README.md
            - files=README.yaml
  needs_cloudposse: &a16
    - or:
        - files~=(mergify|settings|dependabot|renovate|CODEOWNERS|\.github|Makefile|Dockerfile)
        - label~=(cloudposse)
  has_no_changes: &a10
    - and:
        - "#files=0"
  needs_rerun: &a6
    - and:
        - label~=needs-re-run
pull_request_rules:
  - name: label automated pull requests
    conditions:
      - and: *a4
      - and: *a5
    actions:
      label:
        add:
          - auto-update
  - name: label automated pull requests that update readme
    conditions:
      - and: *a5
      - and: *a4
      - files=README.md
    actions:
      label:
        toggle:
          - readme
  - name: re run actions by removing the label autobots-re-run
    conditions:
      - and: *a5
      - and: *a6
    actions:
      label:
        remove:
          - needs-re-run
  - name: run terratest on automated pull requests that update terraform files
    conditions:
      - and: *a5
      - and: *a4
      - and: *a7
    actions:
      comment:
        message: /terratest
  - name: approve automated PRs that only update the markdown files, images or videos
    conditions:
      - and: *a5
      - and: *a8
      - and: *a4
      - head~=auto-update/.*
      - files~=\.(md|gif|png|jpg|mp4)$
    actions:
      review:
        type: APPROVE
  - name: merge automated PRs that only update the markdown files, images or videos
    conditions:
      - and: *a5
      - and: *a8
      - and: *a4
      - "#check-pending=0"
      - head~=auto-update/.*
      - files~=\.(md|gif|png|jpg|mp4)$
    actions:
      merge:
        method: squash
  - name: delete the head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: ask to resolve conflict
    conditions:
      - and: *a5
      - conflict
    actions:
      comment:
        message: 💥 This pull request now has conflicts. Could you fix it @{{author}}?
          🙏
      label:
        toggle:
          - conflict
  - name: ask to rebuild readme
    conditions:
      - and: *a8
      - and: *a5
      - files=README.yaml
      - -files=README.md
    actions:
      comment:
        message: >
          > [!IMPORTANT]

          > `README.md` is out of date.

          >


          Rebuild the `README.md` by running `make readme` and commit the
          changes.


          ```shell

          make init

          make readme

          ```


          Could you fix it @{{author}}? 🙏
  - name: ask for title
    conditions:
      - and: *a8
      - and: *a5
      - -title~=^[0-9A-Za-z]+
    actions:
      comment:
        message: |
          > [!IMPORTANT]
          > #### Title is necessary and should not be empty.
          >
          > Kindly provide a meaningful title for this Pull Request.
  - name: ask for description
    conditions:
      - and: *a8
      - and: *a5
      - -body~=[0-9A-Za-z]{3,}\\s+[0-9A-Za-z]{3,}\\s+[0-9A-Za-z]{3,}
      - body~=(Describe high-level what changed)
    actions:
      comment:
        message: >
          > [!IMPORTANT]

          > #### Description is necessary and should not be empty.

          >

          > Kindly provide details with **what** was changed, **why** it was
          changed.
  - name: remove outdated reviews
    conditions:
      - and: *a5
      - and: *a8
    actions:
      dismiss_reviews:
        changes_requested: true
        approved: true
        message: This Pull Request was updated, so we're dismissing all reviews.
  - name: remove triage label if approved
    conditions:
      - and: *a5
      - "#approved-reviews-by>=1"
    actions:
      label:
        remove:
          - triage
  - name: close automated PRs with persistent merge conflicts quickly
    conditions:
      - and: *a5
      - and: *a4
      - conflict
      - commits[*].date_committer < 1 days ago
    actions:
      close:
        message: |
          This automated PR was closed due to merge conflicts.
  - name: close stale PRs with merge conflicts
    conditions:
      - and: *a5
      - conflict
      - commits[*].date_committer < 30 days ago
      - updated-at < 7 days ago
    actions:
      close:
        message: |
          This PR was closed due to inactivity and merge conflicts. 😭
          Please resolve the conflicts and reopen if necessary.
  - name: close stale pull request after 90 days
    conditions:
      - and: *a5
      - and: *a8
      - commits[*].date_committer < 90 days ago
      - updated-at < 3 days ago
      - label~=(stale)
    actions:
      close:
        message: >
          🚪 We're going close this pull request as it is now stale. Feel free
          to reopen it if you think it's a mistake.
  - name: label stale pull request after 30 days
    conditions:
      - and: *a5
      - and: *a8
      - commits[*].date_committer < 30 days ago
      - updated-at < 7 days ago
      - -label~=(stale|triage)
    actions:
      label:
        toggle:
          - stale
      comment:
        message: >
          Heads up! This pull request looks stale. It will be closed soon, if
          there are no new commits. ⏳
  - name: close pull request waiting on feedback for 1 month
    conditions:
      - and: *a5
      - and: *a8
      - label~=(stale)
      - or:
          - label~=(feedback)
          - "#commented-reviews-by > 0"
          - "#changes-requested-reviews-by > 0"
      - updated-at < 30 days ago
    actions:
      close:
        message: |
          📬 We haven't heard back from you, so we're closing this pull request.
          Feel free to reopen it if you think it's a mistake.
  - name: close pull request marked as invalid, duplicate or won't fix
    conditions:
      - and: *a5
      - and: *a8
      - label~=(duplicate|invalid|wontfix)
    actions:
      close:
        message: |
          ⚰️ This pull request is no longer applicable.
          Feel free to reopen it if you think it's a mistake.
  - name: close pull request that is a work in progress and in active for 1 month
    conditions:
      - and: *a5
      - and: *a8
      - and: *a9
      - commits[*].date_committer < 90 days ago
      - updated-at < 30 days ago
    actions:
      close:
        message: >
          This pull request was marked as a work in progress and looks
          abandoned.

          Feel free to reopen it if you think it's a mistake.
  - name: remove certain labels on close
    conditions:
      - closed
    actions:
      label:
        remove:
          - triage
  - name: close Pull Requests without files changed
    conditions:
      - and: *a5
      - and: *a10
    actions:
      label:
        add:
          - no-changes
      close:
        message: >
          This pull request was automatically closed as it no longer contains
          any changes. 


          This typically happens when another merged pull request has already
          included this request's 

          proposed modifications into the default branch.
  - name: welcome new contributors
    conditions:
      - and: *a5
      - and: *a11
      - and: *a1
      - and: *a12
      - and: *a13
      - and: *a8
      - updated-at < 5 minutes ago
    actions:
      comment:
        message: |
          Thanks @{{author}} for creating this pull request! 

          A maintainer will review your changes shortly. Please don't be discouraged if it takes a while.

          While you wait, make sure to review our [contributor guidelines](https://github.com/cloudposse/.github/blob/main/CONTRIBUTING.md).

          > [!TIP]
          > #### Need help or want to ask for a PR review to be expedited?
          > Join us on [Slack](https://slack.cloudposse.com) in the `#pr-reviews` channel.
  - name: add triage label for new pull requests
    conditions:
      - and: *a5
      - and: *a1
      - "#label=0"
      - "#approved-reviews-by=0"
      - or:
          - created-at > 5 minutes ago
          - commits[*].date_committer > 5 minutes ago
          - updated-at > 7 days ago
    actions:
      label:
        add:
          - triage
  - name: Add needs-test label on new commits
    conditions:
      - and: *a5
      - and: *a8
      - and: *a7
      - and: *a14
      - -label=~needs-test
    actions:
      label:
        add:
          - needs-test
  - name: Remove needs-test label when required tests pass
    conditions:
      - and: *a5
      - and: *a8
      - and: *a15
    actions:
      label:
        remove:
          - needs-test
  - name: add "WIP" label when the title contains "WIP"
    conditions:
      - and: *a5
      - title~=WIP
    actions:
      label:
        toggle:
          - wip
  - name: add "needs-cloudposse" label when restrictions apply to this PR
    conditions:
      - and: *a5
      - and: *a16
    actions:
      label:
        toggle:
          - needs-cloudposse
      comment:
        message: >
          > [!IMPORTANT]

          > #### Cloud Posse Engineering Team Review Required

          > This pull request modifies files that require Cloud Posse's review.
          Please be patient, and a core maintainer will review your changes.

          >

          > To expedite this process, reach out to us on
          [Slack](https://slack.cloudposse.com) in the `#pr-reviews` channel.
  - name: rebase pull request when it's more than 10 commits behind main
    conditions:
      - and: *a5
      - and: *a8
      - "#commits-behind>=10"
    actions:
      rebase:
  - name: rebase pull requests one time when labeled with `rebase`
    conditions:
      - label=rebase
    actions:
      rebase: {}
      label:
        remove:
          - rebase
merge_protections:
  - name: Require terratest
    description: This rule require terratest status
    if:
      - files ~= \.(?!md|gif|png|jpg|mp4).*
      - base = main
    success_conditions:
      - check-success = test/terratest
queue_rules:
  - batch_size: 10
    batch_max_wait_time: 5 m
    checks_timeout: 5 h
    batch_max_failure_resolution_attempts: 3
    merge_method: squash
    update_method: rebase
    name: Test
    branch_protection_injection_mode: queue
    allow_inplace_checks: false
    merge_conditions:
      - and:
          - check-success = test/terratest
