shared:
  is_a_bot: &a4
    or:
      - author=cloudpossebot
      - author=dependabot[bot]
      - author=renovate[bot]
      - author=cloudposse-releaser[bot]
  not_a_bot: &a1
    and:
      - -author=dependabot[bot]
      - -author=renovate[bot]
      - -author=cloudposse-releaser[bot]
  is_internal_contributor: &a10
    and:
      - *a1
      - or:
          - author=@engineering
          - author=@contributors
          - author=@admins
          - author=@bots
          - author=@approvers
          - author=@security
  is_external_contributor: &a9
    and:
      - -author=@engineering
      - -author=@contributors
      - -author=@admins
      - -author=@bots
      - -author=@approvers
      - -author=@security
      - *a1
  is_default_branch: &a11
    or:
      - base=main
      - base=master
  is_release_branch: base~=^release/v\d{1,2}$
  not_wip: &a6
    and:
      - -title~=^(wip|WIP)
      - -label~=(WIP|wip|do-not-merge|do not merge|triage|stale|feedback|help
        needed)
      - -draft
  needs_attention: label~=(triage|stale|feedback|help needed)
  do_not_merge: &a2
    or:
      - label~=(do-not-merge|do not merge)
      - title~=(do-not-merge|do not merge)
  is_wip: &a12
    or:
      - title~=^(wip|WIP)
      - label~=(WIP|wip)
      - *a2
      - label~=(triage|stale|feedback|help needed)
      - draft
  not_in_conflict: &a5
    and:
      - -conflict
      - -label~=(conflict)
  pr_has_metadata:
    and:
      - title~=(^[0-9A-Za-z]+)
      - body~=[0-9A-Za-z]{3,}\\s+[0-9A-Za-z]{3,}\\s+[0-9A-Za-z]{3,}
      - -body~=(Describe high-level what changed)
  is_approved: &a8
    and:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - branch-protection-review-decision=APPROVED
  checks_are_passing: &a7
    and:
      - -check-pending~=Branch\/.*$
      - -check-failure~=Branch\/.*$
  require_terraform_checks_are_passing: &a13
    or:
      - -files~=\.tf$
      - and:
          - check-success=test/bats
          - check-success=test/terratest
          - -status-failure~=^(terratest|terraform)$
  require_codeowners_checks_are_passing:
    or:
      - -files=CODEOWNERS
      - check-success=validate-codeowners
  is_terraform: files~=\.tf$
  is_tests: files~=test/.*$
  is_go_deps: files~=test/(go\.mod|go\.sum)$
  is_components_vendor: files~=(vendor\.ya?ml|component\.ya?ml)$
  is_github_config: files~=\.github/.*$
  is_component: files~=src/.*$
  is_scaffold: files~=\.tflint\.hcl$
  is_open: &a3
    and:
      - -merged
      - -closed
  is_recent_commit: commits[*].date_committer > 1 minutes ago
  readme_updated:
    or:
      - and:
          - -files=README.md
          - -files=README.yaml
      - and:
          - files=README.md
          - files=README.yaml
  needs_cloudposse: &a14
    or:
      - files~=(mergify|settings|dependabot|renovate|CODEOWNERS|\.github|Makefile|Dockerfile)
      - label~=(cloudposse)
  has_no_changes: "#files=0"
  needs_rerun: label~=needs-re-run
pull_request_rules:
  - name: Auto approve auto updates PRs
    conditions:
      - *a3
      - *a4
      - *a5
      - *a6
      - *a7
      - or:
          - files~=test/(go\.mod|go\.sum)$
          - files~=\.tflint\.hcl$
          - files~=(vendor\.ya?ml|component\.ya?ml)$
          - files~=test/.*$
          - files~=\.github/.*$
          - files~=src/.*$
    actions:
      review:
        type: APPROVE
  - name: Set no-release and skip-changelog labels for auto updates
    conditions:
      - *a3
      - *a4
      - and:
          - or:
              - files~=test/(go\.mod|go\.sum)$
              - files~=\.tflint\.hcl$
              - files~=(vendor\.ya?ml|component\.ya?ml)$
              - files~=test/.*$
              - files~=\.github/.*$
    actions:
      label:
        add:
          - no-release
          - skip-changelog
  - name: Add approved PR to merge queue
    conditions:
      - *a3
      - *a5
      - *a6
      - *a8
      - *a7
    actions:
      queue:
  - name: Request approval for PRs
    conditions:
      - *a3
      - or:
          - *a9
          - and:
              - *a10
              - *a5
              - *a7
    actions:
      request_reviews:
        teams:
          - "@contributors"
          - "@approvers"
  - name: label automated pull requests
    conditions:
      - *a4
      - *a3
    actions:
      label:
        add:
          - auto-update
  - name: label automated pull requests that update readme
    conditions:
      - *a3
      - *a4
      - files=README.md
    actions:
      label:
        toggle:
          - readme
  - name: re run actions by removing the label autobots-re-run
    conditions:
      - *a3
      - label~=needs-re-run
    actions:
      label:
        remove:
          - needs-re-run
  - name: delete the head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: ask to resolve conflict
    conditions:
      - *a3
      - conflict
    actions:
      comment:
        message: ðŸ’¥ This pull request now has conflicts. Could you fix it @{{author}}?
          ðŸ™
      label:
        toggle:
          - conflict
  - name: ask to not edit the readme
    conditions:
      - *a3
      - files=README.md
      - -files=README.yaml
    actions:
      comment:
        message: >
          > [!IMPORTANT]

          > Do not edit the `README.md` directly. It's auto-generated from the
          `README.yaml`

          >

          > Please update the `README.yaml` file instead.

          >


          Could you fix it @{{author}}? ðŸ™
  - name: ask for title
    conditions:
      - *a11
      - *a3
      - -title~=^[0-9A-Za-z]+
    actions:
      comment:
        message: |
          > [!IMPORTANT]
          > #### Title is necessary and should not be empty.
          >
          > Kindly provide a meaningful title for this Pull Request.
  - name: ask for description
    conditions:
      - *a11
      - *a3
      - -body~=[0-9A-Za-z]{3,}\\s+[0-9A-Za-z]{3,}\\s+[0-9A-Za-z]{3,}
      - body~=(Describe high-level what changed)
    actions:
      comment:
        message: >
          > [!IMPORTANT]

          > #### Description is necessary and should not be empty.

          >

          > Kindly provide details with **what** was changed, **why** it was
          changed.
  - name: remove outdated reviews
    conditions:
      - *a3
      - *a11
    actions:
      dismiss_reviews:
        changes_requested: true
        approved: true
        message: This Pull Request was updated, so we're dismissing all reviews.
  - name: remove triage label if approved
    conditions:
      - *a3
      - "#approved-reviews-by>=1"
    actions:
      label:
        remove:
          - triage
  - name: close automated PRs with persistent merge conflicts quickly
    conditions:
      - *a3
      - *a4
      - conflict
      - commits[*].date_committer < 1 days ago
    actions:
      close:
        message: |
          This automated PR was closed due to merge conflicts.
  - name: close stale PRs with merge conflicts
    conditions:
      - *a3
      - conflict
      - commits[*].date_committer < 30 days ago
      - updated-at < 7 days ago
    actions:
      close:
        message: |
          This PR was closed due to inactivity and merge conflicts. ðŸ˜­
          Please resolve the conflicts and reopen if necessary.
  - name: close stale pull request after 90 days
    conditions:
      - *a3
      - *a11
      - commits[*].date_committer < 90 days ago
      - updated-at < 3 days ago
      - label~=(stale)
    actions:
      close:
        message: >
          ðŸšª We're going to close this pull request as it is now stale. Feel
          free to reopen it if you think it's a mistake.
  - name: label stale pull request after 30 days
    conditions:
      - *a3
      - *a11
      - commits[*].date_committer < 30 days ago
      - updated-at < 7 days ago
      - -label~=(stale|triage)
    actions:
      label:
        toggle:
          - stale
      comment:
        message: >
          Heads up! This pull request looks stale. It will be closed soon, if
          there are no new commits. â³
  - name: close pull request waiting on feedback for 1 month
    conditions:
      - *a3
      - *a11
      - label~=(stale)
      - or:
          - label~=(feedback)
          - "#commented-reviews-by > 0"
          - "#changes-requested-reviews-by > 0"
      - updated-at < 30 days ago
    actions:
      close:
        message: |
          ðŸ“¬ We haven't heard back from you, so we're closing this pull request.
          Feel free to reopen it.f you think it's a mistake.
  - name: close pull request marked as invalid, duplicate or won't fix
    conditions:
      - *a3
      - *a11
      - label~=(duplicate|invalid|wontfix)
    actions:
      close:
        message: |
          âš°ï¸ This pull request is no longer applicable.
          Feel free to reopen it if you think it's a mistake.
  - name: close pull request that is a work in progress and in active for 1 month
    conditions:
      - *a3
      - *a11
      - *a12
      - commits[*].date_committer < 90 days ago
      - updated-at < 30 days ago
    actions:
      close:
        message: >
          This pull request was marked as a work in progress and looks
          abandoned.

          Feel free to reopen it if you think it's a mistake.
  - name: remove certain labels on close
    conditions:
      - closed
    actions:
      label:
        remove:
          - triage
  - name: close Pull Requests without files changed
    conditions:
      - *a3
      - "#files=0"
    actions:
      label:
        add:
          - no-changes
      close:
        message: >
          This pull request was automatically closed as it no longer contains
          any changes. 


          This typically happens when another merged pull request has already
          included this request's 

          proposed modifications into the default branch.
  - name: welcome new contributors
    conditions:
      - *a3
      - *a6
      - *a1
      - *a5
      - *a9
      - *a11
      - updated-at < 5 minutes ago
    actions:
      comment:
        message: |
          Thanks @{{author}} for creating this pull request! 

          A maintainer will review your changes shortly. Please don't be discouraged if it takes a while.

          While you wait, make sure to review our [contributor guidelines](https://github.com/cloudposse/.github/blob/main/CONTRIBUTING.md).

          > [!TIP]
          > #### Need help or want to ask for a PR review to be expedited?
          > Join us on [Slack](https://slack.cloudposse.com) in the `#pr-reviews` channel.
  - name: add triage label for new pull requests
    conditions:
      - *a3
      - *a1
      - "#label=0"
      - "#approved-reviews-by=0"
      - or:
          - created-at > 5 minutes ago
          - commits[*].date_committer > 5 minutes ago
          - updated-at > 7 days ago
    actions:
      label:
        add:
          - triage
  - name: Add needs-test label on new commits
    conditions:
      - *a3
      - *a11
      - files~=\.tf$
      - commits[*].date_committer > 1 minutes ago
      - -label=~needs-test
    actions:
      label:
        add:
          - needs-test
  - name: Remove needs-test label when required tests pass
    conditions:
      - *a3
      - *a11
      - *a13
    actions:
      label:
        remove:
          - needs-test
  - name: add "WIP" label when the title contains "WIP"
    conditions:
      - *a3
      - title~=WIP
    actions:
      label:
        toggle:
          - wip
  - name: add "needs-cloudposse" label when restrictions apply to this PR
    conditions:
      - *a3
      - *a14
    actions:
      label:
        toggle:
          - needs-cloudposse
      comment:
        message: >
          > [!IMPORTANT]

          > #### Cloud Posse Engineering Team Review Required

          > This pull request modifies files that require Cloud Posse's review.
          Please be patient, and a core maintainer will review your changes.

          >

          > To expedite this process, reach out to us on
          [Slack](https://slack.cloudposse.com) in the `#pr-reviews` channel.
  - name: rebase pull request when it's more than 10 commits behind main
    conditions:
      - *a3
      - *a11
      - "#commits-behind>=10"
    actions:
      rebase:
  - name: rebase pull requests one time when labeled with `rebase`
    conditions:
      - label=rebase
    actions:
      rebase: {}
      label:
        remove:
          - rebase
merge_protections:
  - name: Require terratest
    description: This rule require terratest status
    if:
      - base = main
    success_conditions:
      - *a8
      - *a7
queue_rules:
  - name: Auto Updates
    batch_size: 10
    batch_max_wait_time: 5 m
    checks_timeout: 5 h
    batch_max_failure_resolution_attempts: 3
    merge_method: squash
    update_method: rebase
    branch_protection_injection_mode: queue
    allow_inplace_checks: false
    merge_conditions:
      - check-success = test/terratest
    queue_conditions:
      - and:
          - approved-reviews-by = mergify[bot]
  - name: Default
    batch_size: 10
    batch_max_wait_time: 5 m
    checks_timeout: 5 h
    batch_max_failure_resolution_attempts: 3
    merge_method: squash
    update_method: rebase
    branch_protection_injection_mode: queue
    allow_inplace_checks: false
    merge_conditions:
      - check-success = test/terratest
