---
name: Branch
on:
  pull_request:
    branches:
      - main
      - release/**
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - release/v*
    paths-ignore:
      - '.github/**'
      - 'test/**'
  merge_group:
    types: [checks_requested]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  component:
    uses: cloudposse-terraform-components/.github/.github/workflows/shared-terraform-component.yml@main
    secrets: inherit
