---
name: Branch
on:
  pull_request:
    branches:
      - main
      - release/**
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - release/v*
    paths-ignore:
      - '.github/**'
      - 'test/**'

permissions:
  contents: write
  id-token: write
  pull-requests: write
  statuses: write

jobs:
  component:
    uses: cloudposse-terraform-components/.github/.github/workflows/shared-terraform-component.yml@merge-queue
    secrets: inherit
    
