name: 🚀 Main Branch

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Draft new release
        uses: cloudposse/github-action-auto-release@v1
        with:
          prerelease: false
          publish: true
          config-name: auto-release.yml
