---
name: Queue
on:
  pull_request:
    branches:
      - main
      - release/**
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  pull-requests: write
  id-token: write
  contents: write
  statuses: write

jobs:
  test:
    if: startsWith(github.head_ref, 'mergify/merge-queue/')
    uses: ./.github/workflows/terratest.yaml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      runs-on: '["ubuntu-latest"]'
